---
title: "Demographic of Respondent"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro
- 지난 시간에 설문조사 전처리에 대해 배웠다면 이번에는 경영/사회과학 논문에서 필수적으로 기재해야 하는 `표본의 특성`을 간단한 프로그램으로 요약하는 것을 코딩한다. 

### (1) 주요 패키지
- 이번 포스트부터 [gt](https://gt.rstudio.com/) 패키지를 사용하려고 한다. 
  + gt: [ggplot2](https://ggplot2.tidyverse.org/)와 같이 `Table`를 문법으로 컨트롤 할 수 있도록 구현된 패키지이다. 
  + kableExtra: `HTML`로 출력할 수 있도록 도와주는 패키지이다. 

```{r, warning=FALSE, message=FALSE}
library(readr)
library(dplyr)
```

## I. 데이터 가져오기 
- 우선 데이터를 불러온다. 
```{r, message=FALSE, warning=FALSE}
data <- read_csv('data/thesis_mater.csv') %>% 
  distinct() %>% # 중복데이터 제거
  rename(Position = founder_employee, # 출력을 위한 변수명 정리
         Age = age_of_respondent, 
         Education = Education_Level) %>% 
  slice(-c(1:10))
```
## 2. 표본의 특성 
- 표본의 특성을 산출해본다. 
```{r}
library(table1)
table1(~ Firm_Age + Firm_Size + gender + Position + Age + Education + Business_Area, data=data)
```
